version: "3.8"

services:
  backend:
    build:
      context: ./nest-app
      dockerfile: Dockerfile
    volumes:
      - ./nest-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SECRET_KEY=secretKey
      - NODE_ENV=development
      # 如果使用 HTTPS，可以設置為 production 或啟用 FORCE_SECURE_COOKIE
      # - NODE_ENV=production
      # - FORCE_SECURE_COOKIE=true

  frontend:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    volumes:
      - ./react-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  secure-frontend:
    build:
      context: ./secure-react-app
      dockerfile: Dockerfile
    volumes:
      - ./secure-react-app:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    depends_on:
      - backend

  phishing-site:
    build:
      context: ./phishing-site
      dockerfile: Dockerfile
    volumes:
      - ./phishing-site:/usr/share/nginx/html
    ports:
      - "8080:80"
